// ABOUTME: Interactive setup script for initializing an Amadeus machine.
// ABOUTME: Checks prerequisites, generates config/.env, accepts bypass permissions, tests hub connectivity.

import { spawn, type Subprocess } from "bun";
import * as readline from "readline";
import * as os from "os";
import * as path from "path";
import * as fs from "fs";

const NON_INTERACTIVE = process.argv.includes("--non-interactive");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function step(n: number, total: number, msg: string) {
  console.log(`\n[${n}/${total}] ${msg}`);
}

function success(msg: string) {
  console.log(`  ✓ ${msg}`);
}

function warn(msg: string) {
  console.log(`  ! ${msg}`);
}

function fail(msg: string) {
  console.error(`  ✗ ${msg}`);
}

async function which(bin: string): Promise<string | null> {
  try {
    const result = await Bun.$`which ${bin}`.quiet();
    return result.stdout.toString().trim() || null;
  } catch {
    return null;
  }
}

async function prompt(rl: readline.Interface, question: string, defaultValue?: string): Promise<string> {
  if (NON_INTERACTIVE) return defaultValue ?? "";
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultValue || "");
    });
  });
}

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

async function checkPrerequisites(): Promise<{ missing: string[] }> {
  const missing: string[] = [];

  const bun = await which("bun");
  if (bun) {
    success("bun found");
  } else {
    fail("bun not found — install: curl -fsSL https://bun.sh/install | bash");
    missing.push("bun");
  }

  const agentapi = await which("agentapi");
  if (agentapi) {
    success("agentapi found");
  } else {
    const platform = process.platform === "darwin" ? "darwin" : "linux";
    const arch = process.arch === "arm64" ? "arm64" : "amd64";
    fail(
      `agentapi not found — install:\n` +
        `    curl -fsSL -o /usr/local/bin/agentapi https://github.com/coder/agentapi/releases/latest/download/agentapi-${platform}-${arch}\n` +
        `    chmod +x /usr/local/bin/agentapi`
    );
    missing.push("agentapi");
  }

  const claude = await which("claude");
  if (claude) {
    success("claude CLI found");
  } else {
    fail("claude CLI not found — install: npm install -g @anthropic-ai/claude-code");
    missing.push("claude");
  }

  const gh = await which("gh");
  if (gh) {
    success("gh CLI found");
  } else {
    warn("gh CLI not found (optional) — install: https://cli.github.com");
  }

  const git = await which("git");
  if (git) {
    success("git found");
  } else {
    fail("git not found — install git first");
    missing.push("git");
  }

  return { missing };
}

async function promptForConfig(rl: readline.Interface): Promise<{
  machineName: string;
  hubUrl: string;
  apiKey: string;
  ghToken: string;
}> {
  const defaultName = os.hostname().split(".")[0];

  const machineName = await prompt(rl, "Machine name", defaultName);
  const hubUrl = await prompt(rl, "Hub URL", process.env.AMADEUS_HUB_URL);
  const apiKey = await prompt(rl, "Amadeus API key", process.env.AMADEUS_API_KEY);

  // Try to get GH token from gh CLI
  let ghToken = process.env.GH_TOKEN || "";
  if (!ghToken) {
    try {
      const result = await Bun.$`gh auth token`.quiet();
      ghToken = result.stdout.toString().trim();
      if (ghToken) success("GitHub token detected from gh CLI");
    } catch {
      // gh not authed
    }
  }
  if (!ghToken) {
    ghToken = await prompt(rl, "GitHub token (optional, for PR creation)", "");
  }

  return { machineName, hubUrl, apiKey, ghToken };
}

function generateEnv(config: { apiKey: string; ghToken: string }): string {
  const lines: string[] = [
    "# Generated by setup-machine.ts",
    "",
  ];

  if (config.apiKey) {
    lines.push(`AMADEUS_API_KEY=${config.apiKey}`);
  }
  if (config.ghToken) {
    lines.push(`GH_TOKEN=${config.ghToken}`);
  }

  return lines.join("\n") + "\n";
}

function generateConfig(config: { machineName: string; hubUrl: string }): string {
  return `# Generated by setup-machine.ts
# See amadeus.config.machine.yaml for reference.

global:
  runtimeMode: machine
  port: 5678
  agentName: Amadeus

  machine:
    name: "${config.machineName}"
    hubUrl: "${config.hubUrl}"
    heartbeat: true

  triggerStates:
    - Planning

  useWorktrees: true
  worktreesDir: ~/.amadeus-worktrees

  profilesDir: ./agent-profiles
  defaultProfile: base

  dbPath: ./amadeus-agents.db
`;
}

async function acceptBypassPermissions(): Promise<boolean> {
  // Check if already accepted by looking for the settings file
  const settingsPath = path.join(
    os.homedir(),
    ".claude",
    "settings.json"
  );
  try {
    const settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    if (settings?.bypassPermissions === true) {
      success("Bypass permissions already accepted");
      return true;
    }
  } catch {
    // File doesn't exist or isn't valid JSON — need to accept
  }

  console.log("  Starting temporary agentapi to accept bypass permissions...");

  let agentProcess: Subprocess | null = null;
  const port = 18923; // Unlikely to conflict

  try {
    agentProcess = spawn({
      cmd: [
        "agentapi",
        "server",
        "claude",
        "--port",
        String(port),
        "--",
        "--dangerously-skip-permissions",
      ],
      cwd: process.cwd(),
      stdout: "ignore",
      stderr: "ignore",
    });

    // Wait for server to be ready
    let ready = false;
    for (let i = 0; i < 30; i++) {
      try {
        const res = await fetch(`http://localhost:${port}/status`);
        if (res.ok) {
          ready = true;
          break;
        }
      } catch {
        // Not ready yet
      }
      await Bun.sleep(500);
    }

    if (!ready) {
      fail("agentapi failed to start");
      return false;
    }

    // Wait a moment for initial output
    await Bun.sleep(1500);

    // Check for permissions prompt
    const res = await fetch(`http://localhost:${port}/messages`);
    const data = (await res.json()) as { messages?: { content?: string }[] };

    if (data.messages?.length) {
      const lastMsg = data.messages[data.messages.length - 1];
      if (lastMsg.content?.includes("Yes, I accept")) {
        console.log("  Accepting permissions prompt...");
        await fetch(`http://localhost:${port}/message`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ content: "2", type: "raw" }),
        });

        // Wait for it to process
        await Bun.sleep(2000);
        success("Bypass permissions accepted");
        return true;
      } else {
        success("No permissions prompt detected (may already be accepted)");
        return true;
      }
    } else {
      warn("No messages from agentapi — permissions may already be accepted");
      return true;
    }
  } catch (err) {
    fail(`Error during permissions acceptance: ${err}`);
    return false;
  } finally {
    if (agentProcess) {
      agentProcess.kill();
      // Give it a moment to clean up
      await Bun.sleep(500);
    }
  }
}

async function testHubConnectivity(hubUrl: string, apiKey: string): Promise<boolean> {
  if (!hubUrl) {
    warn("No hub URL configured — skipping connectivity test");
    return true;
  }

  // Test health endpoint
  try {
    const healthRes = await fetch(`${hubUrl}/health`, { signal: AbortSignal.timeout(5000) });
    if (healthRes.ok) {
      success(`Hub health check passed (${hubUrl}/health)`);
    } else {
      fail(`Hub health check failed: HTTP ${healthRes.status}`);
      return false;
    }
  } catch (err) {
    fail(`Cannot reach hub at ${hubUrl}: ${err instanceof Error ? err.message : err}`);
    return false;
  }

  // Test heartbeat auth
  if (apiKey) {
    try {
      const hash = new Bun.CryptoHasher("sha256").update(apiKey).digest("hex");
      const heartbeatRes = await fetch(`${hubUrl}/hub/heartbeat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Machine-Token-Hash": hash,
        },
        body: JSON.stringify({
          machineName: os.hostname().split(".")[0],
          agents: [],
        }),
        signal: AbortSignal.timeout(5000),
      });
      if (heartbeatRes.ok) {
        success("Hub heartbeat auth verified");
      } else {
        fail(`Hub heartbeat auth failed: HTTP ${heartbeatRes.status}`);
        return false;
      }
    } catch (err) {
      fail(`Hub heartbeat failed: ${err instanceof Error ? err.message : err}`);
      return false;
    }
  }

  return true;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("=== Amadeus Machine Setup ===\n");

  const projectRoot = path.resolve(import.meta.dir, "..");
  const totalSteps = 8;
  let currentStep = 0;

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  try {
    // Step 1: Check prerequisites
    currentStep++;
    step(currentStep, totalSteps, "Checking prerequisites...");
    const { missing } = await checkPrerequisites();
    if (missing.length > 0) {
      console.log(`\n  Install the missing tools above and re-run this script.`);
      process.exit(1);
    }

    // Step 2: Prompt for config
    currentStep++;
    step(currentStep, totalSteps, "Configuration...");
    const config = await promptForConfig(rl);

    // Step 3: Generate .env
    currentStep++;
    step(currentStep, totalSteps, "Generating .env...");
    const envPath = path.join(projectRoot, ".env");
    if (fs.existsSync(envPath)) {
      warn(".env already exists — skipping (delete to regenerate)");
    } else {
      const envContent = generateEnv(config);
      fs.writeFileSync(envPath, envContent);
      success("Created .env");
    }

    // Step 4: Generate amadeus.config.yaml
    currentStep++;
    step(currentStep, totalSteps, "Generating amadeus.config.yaml...");
    const configPath = path.join(projectRoot, "amadeus.config.yaml");
    if (fs.existsSync(configPath)) {
      warn("amadeus.config.yaml already exists — skipping (delete to regenerate)");
    } else {
      const configContent = generateConfig(config);
      fs.writeFileSync(configPath, configContent);
      success("Created amadeus.config.yaml");
    }

    // Step 5: Create worktrees directory
    currentStep++;
    step(currentStep, totalSteps, "Creating worktrees directory...");
    const worktreesDir = path.join(os.homedir(), ".amadeus-worktrees");
    if (fs.existsSync(worktreesDir)) {
      success(`${worktreesDir} already exists`);
    } else {
      fs.mkdirSync(worktreesDir, { recursive: true });
      success(`Created ${worktreesDir}`);
    }

    // Step 6: Install dependencies
    currentStep++;
    step(currentStep, totalSteps, "Installing dependencies...");
    await Bun.$`bun install`.cwd(projectRoot);
    success("Dependencies installed");

    // Step 7: Accept bypass permissions
    currentStep++;
    step(currentStep, totalSteps, "Checking bypass permissions...");
    await acceptBypassPermissions();

    // Step 8: Test hub connectivity
    currentStep++;
    step(currentStep, totalSteps, "Testing hub connectivity...");
    await testHubConnectivity(config.hubUrl, config.apiKey);

    // Summary
    console.log("\n=== Setup Complete ===\n");
    console.log("To start Amadeus:");
    console.log(`  cd ${projectRoot}`);
    console.log("  bun src/server.ts\n");

    if (!config.hubUrl) {
      warn("No hub URL configured — set global.machine.hubUrl in amadeus.config.yaml");
    }
    if (!config.apiKey) {
      warn("No API key configured — set AMADEUS_API_KEY in .env");
    }
  } finally {
    rl.close();
  }
}

main().catch((err) => {
  console.error("\nSetup failed:", err);
  process.exit(1);
});
